[env:heltec-v3-faktec] 
extends = esp32s3_base
board = heltec_wifi_lora_32_V3
board_level = pr
board_check = true
board_build.partitions = default_8MB.csv
build_unflags = 
  -flto
build_flags = 
  ${esp32s3_base.build_flags}
  -fno-lto
  -D HELTEC_V3
  -I variants/esp32s3/heltec_v3_faktec
  -D GPS_POWER_TOGGLE
  -D ST7920_CLK=33
  -D ST7920_MOSI=34
  -D ST7920_CS=5
  -D ST7920_RST=21
  -D ST7920_V0=3
  -D USE_ST7920
lib_deps = 
  ${esp32s3_base.lib_deps}
  U8g2